### ISSUE TITLE
Parse subscription txt file failed with following command

### ISSUE THREAD

**Issue by jm0477** [boypt/vmess2json#4]
$ cat v2ray.txt | sudo ./vmess2json.py --inbounds http:1081,socks:1080 --output /etc/v2ray/config.json 
Traceback (most recent call last):
  File "./vmess2json.py", line 725, in <module>
    if int(vc["v"]) != 2:
TypeError: 'NoneType' object is not subscriptable

The v2ray.txt was the file provided by ssr provider. and not modified, just name changed

Do you have any idea why this happed? 
I tried on Debian9 and Ubuntu 18.04  none of them works. all the same error.

**Comment by boypt** [comment]
there's a bug dealing with schemes, fixed in 1b2325a .
But this script works only with `vmess://` and `ss://`, not ssr.
