### ISSUE TITLE
Could you please let the  ``--outbound  --inbounds socks:port''  works?

### ISSUE THREAD

**Issue by hongyi-zhao** [boypt/vmess2json#7]
Hi,

The vmess2json.py 's  --outbound option will only out outbound config.   I want to combine the following two part in the out of config:

  --outbound  --inbounds 

Say, I want to run the following:

vmess2json.py --outbound --inbounds socks:8888

Could you please let this work?

**Comment by boypt** [comment]
just remove the --outbound option, the program will output a full
configuration. with inbounds and outbounds

hongyi-zhao <notifications@github.com> 于 2019年9月13日周五 16:51写道：
